controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

  leg_rf_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ right_front_leg_joint_motor ]
    velocity:
      joint: right_front_first_leg_joint
      search_velocity: -1.4
      vel_threshold: 0.05
      pid: { p: 2.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
  #  test_effort_controller1:
  #    type: effort_controllers/JointPositionController
  #    joint: right_front_first_leg_joint
  #    pid: { p: 3.0, i: 0., d: 0.001, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
  #  test_velocity_controller1:
  #    type: effort_controllers/JointVelocityController
  #    joint: right_front_first_leg_joint
  #    pid: { p: 3.0, i: 0., d: 0.001, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
  #
  leg_lf_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ left_front_leg_joint_motor ]
    velocity:
      joint: left_front_first_leg_joint
      search_velocity: -1.4
      vel_threshold: 0.05
      pid: { p: 2.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
  #  test_effort_controller2:
  #    type: effort_controllers/JointPositionController
  #    joint: left_front_first_leg_joint
  #    pid: { p: 3.0, i: 0., d: 0.001, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
  #  test_velocity_controller2:
  #    type: effort_controllers/JointVelocityController
  #    joint: left_front_first_leg_joint
  #    pid: { p: 3.0, i: 0., d: 0.001, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
  #
  leg_lb_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ left_back_leg_joint_motor ]
    velocity:
      joint: left_back_first_leg_joint
      search_velocity: 1.4
      vel_threshold: 0.05
      pid: { p: 2.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
  #  test_effort_controller3:
  #    type: effort_controllers/JointPositionController
  #    joint: left_back_first_leg_joint
  #    pid: { p: 3.0, i: 0., d: 0.001, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
  #  test_velocity_controller3:
  #    type: effort_controllers/JointVelocityController
  #    joint: left_back_first_leg_joint
  #    pid: { p: 3.0, i: 0., d: 0.001, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
  #
  leg_rb_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ right_back_leg_joint_motor ]
    velocity:
      joint: right_back_first_leg_joint
      search_velocity: 1.4
      vel_threshold: 0.05
      pid: { p: 2.0, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }
  #  test_effort_controller4:
  #    type: effort_controllers/JointPositionController
  #    joint: right_back_first_leg_joint
  #    pid: { p: 3.0, i: 0., d: 0.001, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
  #  test_velocity_controller4:
  #    type: effort_controllers/JointVelocityController
  #    joint: right_back_first_leg_joint
  #    pid: { p: 3.0, i: 0., d: 0.001, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }


  four_link_vmc_controller:
    type: rm/VMCController
    left_joint: right_front_first_leg_joint
    right_joint: right_back_first_leg_joint
    vmc_bias_angle: 3.49
    pid_angle: { p: 30, i: 0, d: 2, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_length: { p: 400.0, i: 2, d: 20, i_clamp_max: 40.0, i_clamp_min: -40.0, antiwindup: true, publish_state: true }

  shooter_controller:
    type: rm_shooter_controllers/Controller
    publish_rate: 50
    friction_left:
      joint: "left_friction_wheel_joint"
      pid: { p: 0.0007, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    friction_right:
      joint: "right_friction_wheel_joint"
      pid: { p: 0.0007, i: 0.005, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
    trigger:
      joint: "trigger_joint"
      pid: { p: 40.0, i: 0.0, d: 1.5, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
    push_per_rotation: 9
    push_qd_threshold: 0.90
    block_effort: 2.2
    block_speed: 0.1
    block_duration: 0.05
    block_overtime: 0.5
    anti_block_angle: 0.46
    anti_block_threshold: 0.1
    forward_push_threshold: 0.22
    exit_push_threshold: 0.25

  trigger_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ trigger_joint_motor ]
    velocity:
      joint: trigger_joint
      search_velocity: 3.1415
      vel_threshold: 0.2
      pid: { p: 0.3, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }


  legged_balance_controller:
    type: rm/LeggedBalanceController
    left_wheel:
      joint: left_wheel_joint
      pid: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    right_wheel:
      joint: right_wheel_joint
      pid: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_follow: { p: 7.0, i: 0, d: 0.3, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_left_leg: { p: 480.0, i: 5.0, d: 20, i_clamp_max: 20.0, i_clamp_min: -20.0, antiwindup: true, publish_state: true }
    pid_right_leg: { p: 480.0, i: 5.0, d: 20, i_clamp_max: 20.0, i_clamp_min: -20.0, antiwindup: true, publish_state: true }
    pid_theta_diff: { p: 40.0, i: 0.0, d: 0.1, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_roll: { p: 300.0, i: 8, d: 5, i_clamp_max: 10.0, i_clamp_min: -10.0, antiwindup: true, publish_state: true }
    pid_center_gravity: { p: 0.0, i: 0, d: 0, i_clamp_max: 0.4, i_clamp_min: -0.4, antiwindup: true, publish_state: true }
    pid_length_diff: { p: 0.0, i: 0, d: 0, i_clamp_max: 0.0, i_clamp_min: -0.0, antiwindup: true, publish_state: true }
    leg_protect_angle: 0.9  #0.9
    pitch_protect_angle: 1.1 #1.1
    roll_protect_angle: 1.0
    leg_protect_length: 0.1
    ground_support_threshold: 3
    vmc_bias_angle: 3.49

    gravity_compensation_vel_threshold: 0.1
    gravity_compensation_pos_threshold: 0.5

    jump_over_time: 2.0
    p1: -241100
    p2: 170300
    p3: 39310
    p4: 3234

  legged_balance_lqr_controller:
    type: rm_chassis_controllers/LeggedBalanceLQRController
    # ChassisBase
    publish_rate: 100
    enable_odom_tf: true
    publish_odom_tf: true
    power:
      effort_coeff: 0
      vel_coeff: 0
      power_offset: 0
    twist_angular: 0.5233
    timeout: 0.1
    pid_follow: { p: 7.0, i: 0, d: 0.3, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]
    # BalanceLQRController
    left_wheel:
      joint: left_wheel_joint
      pid: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    right_wheel:
      joint: right_wheel_joint
      pid: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_left_leg: { p: 2500.0, i: 100, d: 250, i_clamp_max: 10.0, i_clamp_min: -10.0, antiwindup: true, publish_state: true }
    pid_right_leg: { p: 2500.0, i: 100, d: 250, i_clamp_max: 10.0, i_clamp_min: -10.0, antiwindup: true, publish_state: true }
    pid_theta_diff: { p: 10.0, i: 0.0, d: 0.1, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    pid_roll: { p: 2000.0, i: 50, d: 50, i_max: 50.0, i_min: -50.0, antiwindup: true, publish_state: true }
    vmc: { l_a: 0.054, l_u: 0.15, l_d: 0.25 }
    dynamics: { d: 0.419, l_c: 0.03, r: 0.125, massBody: 0.56, massLeg: 0.56, massWheel: 0.4657, jWheel: 0.005773, g: 9.8,
                kWheel: 0.002907, i1: 2.918e-1, i2: 2.384e-1, i3: 2.515e-1 }
    block_angle: 0.7
    q: [ 0.5, 100, 100, 50, 100, 10, 0.5, 0.5, 0.5, 0.5 ]
    r: [ 0.5, 0.5, 0.5, 0.5 ]
    leg_length: # Change leg length in leg_cmd topic
      - 0.11
      - 0.15
      - 0.18
      - 0.22
      - 0.26
    #powerCoeffEffort: 1.339, powerCoeffVel: 0.016, powerOffset: 9.8

  orientation_controller:
    type: rm_orientation_controller/Controller
    publish_rate: 100
    name: "gimbal_imu"
    frame_source: "odom"
    frame_target: "base_link"

  gimbal_controller:
    type: rm_gimbal_controllers/Controller
    yaw:
      joint: "yaw_joint"
      pid: { p: 13, i: 0, d: 0.8, i_clamp_max: 0.3, i_clamp_min: -0.3, antiwindup: true, publish_state: true }
      k_chassis_vel: 0.03
    pitch:
      joint: "pitch_joint"
      pid: { p: 5.0, i: 0, d: 0.15, i_clamp_max: 0, i_clamp_min: 0, antiwindup: true, publish_state: true }
      k_v: 0.0
    chassis_vel:
      num_data: 20
      debug: true
    imu_name: "gimbal_imu"
    feedforward:
      gravity: 8.05
      enable_gravity_compensation: false
      mass_origin: [ 0.0,0.005158,0.02901 ]
    bullet_solver:
      resistance_coff_qd_10: 0.45
      resistance_coff_qd_15: 0.01
      resistance_coff_qd_16: 1.5
      resistance_coff_qd_18: 0.55
      resistance_coff_qd_30: 0.01
      g: 9.81
      delay: 0.06
      dt: 0.001
      timeout: 0.001
      publish_rate: 50

