can_motors:
  - can_id: 1
    can_bus: 0
    name: "right_front_first_joint_motor"
    type: "DM8009"
    need_calibration: true
  - can_id: 2
    can_bus: 0
    name: "right_back_first_joint_motor"
    type: "DM8009"
    need_calibration: true
  - can_id: 1
    can_bus: 1
    name: "left_back_first_joint_motor"
    type: "DM8009"
    need_calibration: true
  - can_id: 2
    can_bus: 1
    name: "left_front_first_joint_motor"
    type: "DM8009"
    need_calibration: true
